name: EnCorinVest
description: "EnCorinVest Apk By: Kanagawa Yamada"
publish_to: 'none'
version: 21.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.12.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Medium.ttf
          weight: 500
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
        - asset: assets/fonts/Orbitron-Black.ttf
          weight: 900
  uses-material-design: true
  assets:
  - assets/logo.png
  - assets/KLC.png

